// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.brophy.protocol;

public final class GameOuterClass {
  private GameOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_LoadGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_LoadGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_LoadGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_LoadGameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\004game\"/\n\017LoadGameRequest\022\014\n" +
      "\004name\030\001 \001(\t\022\016\n\006gameId\030\002 \001(\t\"6\n\020LoadGameR" +
      "esponse\022\016\n\006gameId\030\001 \001(\t\022\022\n\ninstanceId\030\002 " +
      "\001(\t2C\n\004Game\022;\n\010LoadGame\022\025.game.LoadGameR" +
      "equest\032\026.game.LoadGameResponse\"\000BC\n\023com." +
      "brophy.protocolP\001Z*github.com/bpatel85/l" +
      "earn-arcore/server/pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_game_LoadGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_LoadGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_LoadGameRequest_descriptor,
        new java.lang.String[] { "Name", "GameId", });
    internal_static_game_LoadGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_LoadGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_LoadGameResponse_descriptor,
        new java.lang.String[] { "GameId", "InstanceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
