// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.brophy.protocol;

public interface LoadGameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.LoadGameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string gameId = 1;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 1;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();

  /**
   * <code>string instanceId = 2;</code>
   * @return The instanceId.
   */
  java.lang.String getInstanceId();
  /**
   * <code>string instanceId = 2;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();
}
