// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package com.brophy.protocol;

public interface LoadGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:game.LoadGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string gameId = 2;</code>
   * @return The gameId.
   */
  java.lang.String getGameId();
  /**
   * <code>string gameId = 2;</code>
   * @return The bytes for gameId.
   */
  com.google.protobuf.ByteString
      getGameIdBytes();
}
